productLineId: line0001
productId: shoppers
appId: sp101
businessDept: SP
appName: shoppers-api
deploymentPlatform: aks
language: Java

cate1:
  enabled: false
  ingressMode: false
  liveServiceName:
  stageServiceName:

config:
  name:

container:
  replicaCount: 1
  port: 8001
  protocol: HTTPS
  cpuLimit: 1500m
  cpuRequest: 500m
  memoryLimit: 10Gi
  memoryRequest: 10Gi
  enableHttps: true

environment:
  csp: azure
  apmtrace_env: dev-central
  http_client_tag_query_string: true
  http_server_tag_query_string: true
  trace_analytics_enabled: true
  trace_db_client: true
  trace_agent_enabled: true
  jms_analytics_enabled: true
  jdbc_analytics_enabled: true
  deploy_timestamp:
  initial_mem: 1G
  max_mem: 8G
  name: dev_central
  namespace: shoppers-aks-ns-dev

hpa:
  enabled: true
  cpuTargetPercent: 50
  maxReplicaCount: 4
  minReplicaCount: 3

image:
  livenessProbe:
    failureThreshold: 3
    successThreshold: 1
    httpPath: shoppers-api/monitoring/health/liveness
    initialDelay: 60
    period: 60
    timeout: 30
  pullPolicy: IfNotPresent
  pullSecrets: dockercredentials
  readinessProbe:
    failureThreshold: 3
    successThreshold: 1
    httpPath: shoppers-api/monitoring/health/readiness
    initialDelay: 30
    period: 30
    timeout: 30
  registry: shoppers-app.com
  repository: shoppers/shoppers-api
  tag: #IMAGE-VERSION#

ingress:
  enabled: true
  path: /
  load_balance: shoppers-api-dev.com
  internal_load_balancer: shoppers-api-dev.shoppers-dev-central.azure-dev.com
  internal_load_balancer_stage: shoppers-api-dev.shoppers-dev-central.azure-dev.com
  tls_secret: sp101-shoppers-api-secret
  ssl_redirect: true
  backend_protocol: HTTPS
  proxy_read_timeout: 600
  proxy_send_timeout: 600
  proxy_connect_timeout: 600
  proxy_body_size: 100M
  proxy_buffer_size: 1M
  client_max_body_size: 100M
  client_body_buffer_size: 1M

securityContext:
  allowedranges:
  allowedRanges:
    runAsUser: 1000
    runAsGroup: 1000
    supplementalGroups:
      - 1000
      - 1001
  isRunAsNonRoot: true

logIndex: logIndex: pr-shoppers

logging:
  service: sp101-shoppers-api
  source: java

orgid: sp

pdb:
  enabled: true
  minAvailable: 50%

resources:

deployment:
  createdby: IBS

splunkcloud:
  enabled: true
  splunkindex: pr-shoppers

service:
  port: 8001
  type: ClusterIP
  sessionAffinity: None

rollingUpdate:
  maxUnavailable: 50%
  maxSurge: 100%

vaultEnv: DEV
vaultRole: pr_shoppers_sp101_dev_role
terminationGracePeriod: 30






