package com.ibssoln.shoppers.soap.outbound.inventory.client;

import com.ibssoln.shoppers.soap.outbound.inventory.dto.ObjectFactory;
import com.ibssoln.shoppers.soap.outbound.inventory.dto.ProvideInventoryCANRequest;
import com.ibssoln.shoppers.soap.outbound.inventory.dto.ProvideInventoryCANResponse;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "inventoryProviderServicePort", targetNamespace = "http://inventory.inbound.soap.shoppers.ibssoln.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InventoryProviderServicePort {

    /**
     * 
     * @param provideInventoryCANRequest
     * @return
     *     returns com.ibssoln.shoppers.soap.outbound.inventory.dto.ProvideInventoryCANResponse
     */
    @WebMethod
    @WebResult(name = "provideInventoryCANResponse", targetNamespace = "http://inventory.inbound.soap.shoppers.ibssoln.com/", partName = "provideInventoryCANResponse")
    public ProvideInventoryCANResponse provideInventoryCAN(
        @WebParam(name = "provideInventoryCANRequest", targetNamespace = "http://inventory.inbound.soap.shoppers.ibssoln.com/", partName = "provideInventoryCANRequest")
        ProvideInventoryCANRequest provideInventoryCANRequest);

}
